#!/usr/bin/env node
// Build the BomDom viewer template: bundle web/bomdom/main.js into a single
// minified classic-script IIFE, inline it (plus CSS and license block) into
// shell.html, and write src/picturebom/assets/bomdom/viewer_template.html.
//
// The runtime __BOMDOM_*__ sentinels are substituted later by Python
// (picturebom.bomdom.build_html) and MUST survive this build untouched.
//
// Run:  cd web && npm run build     (or: node scripts/build_viewer.mjs)

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { gzipSync } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { createRequire } from 'node:module';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '..');
const webDir = path.join(repo, 'web');
const srcDir = path.join(webDir, 'bomdom');
const outFile = path.join(repo, 'src', 'picturebom', 'assets', 'bomdom', 'viewer_template.html');

// scripts/ has no node_modules; resolve esbuild (and three) from web/.
const requireFromWeb = createRequire(path.join(webDir, 'package.json'));
const esbuild = requireFromWeb('esbuild');

function fail(msg) {
  console.error(`\nBUILD FAILED: ${msg}\n`);
  process.exit(1);
}

const fmtKB = (n) => `${(n / 1024).toFixed(1)} KB`;

// ---------------------------------------------------------------------------
// 1. Guard the DRACOLoader private API our InlineDRACOLoader subclass overrides.
//    If a future three upgrade removes/renames _loadLibrary, Draco decoding
//    would silently try to fetch() on a file:// page — fail the build instead.
// ---------------------------------------------------------------------------
const dracoLoaderPath = path.join(webDir, 'node_modules/three/examples/jsm/loaders/DRACOLoader.js');
const dracoLoaderSrc = readFileSync(dracoLoaderPath, 'utf8');
if (!/_loadLibrary\s*\(\s*url\s*,\s*responseType\s*\)/.test(dracoLoaderSrc)) {
  fail(`DRACOLoader.prototype._loadLibrary not found in ${dracoLoaderPath}.\n` +
    'InlineDRACOLoader (web/bomdom/inline-draco.js) overrides this private API to keep the\n' +
    'viewer network-free; the installed three version no longer has it. Update the subclass.');
}

// ---------------------------------------------------------------------------
// 2. Regenerate the embedded Draco decoder module (wrapper JS as text, wasm
//    as gzip+base64 — inflated at runtime through the same gunzip path the
//    payload uses).
// ---------------------------------------------------------------------------
const dracoDir = path.join(webDir, 'node_modules/three/examples/jsm/libs/draco/gltf');
const wrapperJs = readFileSync(path.join(dracoDir, 'draco_wasm_wrapper.js'), 'utf8');
const wasm = readFileSync(path.join(dracoDir, 'draco_decoder.wasm'));
const wasmGzB64 = gzipSync(wasm, { level: 9 }).toString('base64');
writeFileSync(path.join(srcDir, '_generated_draco.js'),
  '// GENERATED by scripts/build_viewer.mjs on every build — do not edit, do not commit.\n' +
  `export const DRACO_WRAPPER_JS = ${JSON.stringify(wrapperJs)};\n` +
  `export const DRACO_WASM_GZ_B64 = ${JSON.stringify(wasmGzB64)};\n`);

// ---------------------------------------------------------------------------
// 3. Bundle. A non-minified pass runs first purely as a canary: it surfaces
//    resolution/syntax problems with readable output before minification.
// ---------------------------------------------------------------------------
const buildOptions = {
  entryPoints: [path.join(srcDir, 'main.js')],
  bundle: true,
  write: false,
  format: 'iife',
  platform: 'browser',
  target: ['chrome109', 'edge109'],
  charset: 'utf8',
  legalComments: 'none',
  absWorkingDir: webDir,
};

let unminified;
try {
  unminified = await esbuild.build({ ...buildOptions, minify: false });
} catch (e) {
  fail(`esbuild (unminified canary pass): ${e.message}`);
}
let result;
try {
  result = await esbuild.build({ ...buildOptions, minify: true });
} catch (e) {
  fail(`esbuild (minified pass): ${e.message}`);
}
let js = result.outputFiles[0].text.trim();
// The bundle lives inside an inline <script>; a literal "</script" in any
// string constant would terminate it early.
js = js.replace(/<\/script/gi, '<\\/script');
if (js.includes('__BOMDOM_')) {
  fail('The JS bundle contains a __BOMDOM_ sentinel literal; runtime code must read the ' +
    'payload from the DOM slots, never embed sentinel strings (Python replaces ALL occurrences).');
}

// ---------------------------------------------------------------------------
// 4. CSS
// ---------------------------------------------------------------------------
const rawCss = readFileSync(path.join(srcDir, 'style.css'), 'utf8');
const cssMin = (await esbuild.transform(rawCss, { loader: 'css', minify: true })).code.trim();

// ---------------------------------------------------------------------------
// 5. Assemble the template
// ---------------------------------------------------------------------------
const LICENSES = `<!--
Third-party components bundled in this file:
  three.js r178 (MIT License, (c) 2010-2025 three.js authors)
  three-mesh-bvh 0.9.1 (MIT License, (c) 2019 Garrett Johnson)
  Google Draco decoder wasm (Apache License 2.0, (c) Google LLC)
  write-excel-file 2.3.2 (MIT License, (c) Nikolay Kuchumov)
  jszip 3.10 (MIT License, (c) 2009-2016 Stuart Knightley et al; bundled by write-excel-file)
  file-saver 2.0 (MIT License, (c) 2016 Eli Grey; bundled by write-excel-file)
-->`;

let html = readFileSync(path.join(srcDir, 'shell.html'), 'utf8');
for (const [slot, content] of [
  ['%%VIEWER_CSS%%', cssMin],
  ['%%VIEWER_JS%%', js],
  ['%%LICENSES%%', LICENSES],
]) {
  if (!html.includes(slot)) fail(`shell.html is missing the ${slot} slot`);
  html = html.replace(slot, () => content); // function form: content may contain $-patterns
}
if (html.includes('%%')) fail('unfilled %% slot remains in the assembled template');

// The runtime sentinels must survive exactly once each, and the payload slots
// must keep the single-quoted id attributes scripts/smoke_bomdom.py extracts by.
const count = (s, sub) => s.split(sub).length - 1;
for (const sentinel of ['__BOMDOM_PAYLOAD_JSON__', '__BOMDOM_GLB_GZ_B64__', '__BOMDOM_MODE__',
                        '__BOMDOM_CONFIG__']) {
  const n = count(html, sentinel);
  if (n !== 1) fail(`sentinel ${sentinel} appears ${n} times in the output (expected exactly 1)`);
}
for (const id of ['bomdom-mode', 'bomdom-meta', 'bomdom-glb']) {
  if (!html.includes(`<script type='text/plain' id='${id}'>`)) {
    fail(`payload slot <script type='text/plain' id='${id}'> not found ` +
      '(single-quoted attributes are a contract with scripts/smoke_bomdom.py _extract)');
  }
}

mkdirSync(path.dirname(outFile), { recursive: true });
writeFileSync(outFile, html);

console.log('BomDom viewer template built OK');
console.log(`  JS bundle (minified):   ${fmtKB(js.length)}  (unminified canary: ${fmtKB(unminified.outputFiles[0].text.length)})`);
console.log(`  CSS (minified):         ${fmtKB(cssMin.length)}`);
console.log(`  Draco wasm gz+b64:      ${fmtKB(wasmGzB64.length)}  (raw wasm ${fmtKB(wasm.length)})`);
console.log(`  Template total:         ${fmtKB(html.length)}`);
console.log(`  -> ${outFile}`);
